<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Moved</name>
   <tag></tag>
   <elementGuidId>cf3c8c66-3e7c-42b2-a497-0e26ae4d1cd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#moved</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='moved']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Moved&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>214a5e61-d8bf-41a6-a5ee-3c6d3c702aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>moved</value>
      <webElementGuid>127899b7-8e46-4a6e-907d-f8e6a85e2037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>8a2f3cdb-9cce-4b57-8cb7-3e6445069318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Moved</value>
      <webElementGuid>05cf445f-7179-4498-a389-9b94fb0bb112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;moved&quot;)</value>
      <webElementGuid>989fc386-c92f-4ae9-acea-3612f4b67b77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='moved']</value>
      <webElementGuid>a4e15032-3755-417b-94f1-ff0f6b3a0d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='linkWrapper']/p[5]/a</value>
      <webElementGuid>105f512d-644a-4cb9-aba0-bb7273ab710d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Moved')]</value>
      <webElementGuid>53ac411e-059c-4734-a5be-ab02e9b2fd24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Content'])[1]/following::a[1]</value>
      <webElementGuid>0ec79c08-fd67-46c7-9801-ee12999b631b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created'])[1]/following::a[2]</value>
      <webElementGuid>8df0deee-a1d5-40c0-adc9-7ea538d524f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bad Request'])[1]/preceding::a[1]</value>
      <webElementGuid>59333b73-0883-458e-b95c-840a4d8920d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unauthorized'])[1]/preceding::a[2]</value>
      <webElementGuid>5435cc0f-0397-4fff-a015-e25495571b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Moved']/parent::*</value>
      <webElementGuid>3e442d80-c0ed-4480-bc85-1813cd93cee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[3]</value>
      <webElementGuid>0d02e1a7-8f48-4e07-8daf-a845149c36f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]/a</value>
      <webElementGuid>0ed466b2-bd2a-4ea7-99c6-c35bc42b7342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'moved' and @href = 'javascript:void(0)' and (text() = 'Moved' or . = 'Moved')]</value>
      <webElementGuid>0d25a2fa-7993-45ac-bfbb-c49fcfe45b97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
