<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Elements_banner-image</name>
   <tag></tag>
   <elementGuidId>2c482155-a247-474f-8da0-676309c4d346</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.banner-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Selenium Online Training&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1266f231-91b2-406b-9166-8e008a24e155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>banner-image</value>
      <webElementGuid>d1874362-a48d-4454-8e19-acea290f4052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/WB.svg</value>
      <webElementGuid>7bc493f9-de70-4948-89bc-ca0a8b503f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Selenium Online Training</value>
      <webElementGuid>c4e8d38a-fd50-48d4-9fcb-9f5c9f7065e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;body-height&quot;]/div[@class=&quot;home-content&quot;]/div[@class=&quot;home-banner&quot;]/a[1]/img[@class=&quot;banner-image&quot;]</value>
      <webElementGuid>805dcffa-21d2-42b2-9804-fcfdc9087794</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/a/img</value>
      <webElementGuid>6daa873a-b267-492f-9b8a-34ca94018efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Selenium Online Training']</value>
      <webElementGuid>3fb6e1f6-63d8-4251-927f-d279f14da618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/img</value>
      <webElementGuid>98487018-2b98-4eaf-9d9f-f3e6d33d7cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/WB.svg' and @alt = 'Selenium Online Training']</value>
      <webElementGuid>37550e84-9b6c-4363-98cc-5bf31001a25d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
