<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Currently you are not logged into the_c7ecc4</name>
   <tag></tag>
   <elementGuidId>af1004d9-b930-470d-ba12-80a1ef86e196</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='notLoggin-label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#notLoggin-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Currently you are not logged into the Book Store application, please visit the l&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>77f46564-b4e8-42a4-b4c6-2be5d26a2e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label</value>
      <webElementGuid>f797a27a-41cd-4c28-932d-89b4c924c868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notLoggin-label</value>
      <webElementGuid>e40cf2e0-6de6-47eb-b665-2eaa1e292802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Currently you are not logged into the Book Store application, please visit the login page to enter or register page to register yourself.</value>
      <webElementGuid>3f01370c-7f24-44e7-88c7-0e054256c192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notLoggin-label&quot;)</value>
      <webElementGuid>d071a54f-212b-44d1-bd22-9d8b7639aecd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='notLoggin-label']</value>
      <webElementGuid>16baf07d-123d-4cbd-980e-61bf57f7ac07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notLoggin-wrapper']/div/label</value>
      <webElementGuid>d17816cc-5a69-4b00-9592-c4810dc7a0ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Store API'])[1]/following::label[1]</value>
      <webElementGuid>7e7b62de-933b-454b-a25d-d4d7717a9bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/following::label[1]</value>
      <webElementGuid>a6ba7abd-82fc-46c7-a422-c3a8ef3c66df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Currently you are not logged into the Book Store application, please visit the']/parent::*</value>
      <webElementGuid>57d565a3-a4a5-4a6b-88d6-83ebc9f4efe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>e47989df-e674-43d7-8b6b-e1a9da1c60e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'notLoggin-label' and (text() = 'Currently you are not logged into the Book Store application, please visit the login page to enter or register page to register yourself.' or . = 'Currently you are not logged into the Book Store application, please visit the login page to enter or register page to register yourself.')]</value>
      <webElementGuid>af1326b8-f0a4-4c67-bfef-dc726e16056c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
