<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_This text has random Id</name>
   <tag></tag>
   <elementGuidId>b0e80846-28ae-490c-8a78-9613d8ab13f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#32AZ6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div[2]/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;This text has random Id&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4957891a-4049-4484-acd3-d5ee6cc749f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>32AZ6</value>
      <webElementGuid>a3c649fb-a0ad-4594-8808-1adf029972d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This text has random Id</value>
      <webElementGuid>90a23308-598e-4cb3-b9af-ea0e35ebc043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;32AZ6&quot;)</value>
      <webElementGuid>ac029418-64c4-43de-b05f-b678e26905e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='32AZ6']</value>
      <webElementGuid>38d64d00-1881-495b-ae69-bed00f44226d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[2]/div[2]/p</value>
      <webElementGuid>43ea5005-5ebd-4128-8fd1-4740983e1156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dynamic Properties'])[2]/following::p[1]</value>
      <webElementGuid>5b19f86d-9ee1-4b09-9bb2-c6fa7caad657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Store API'])[1]/following::p[1]</value>
      <webElementGuid>d352e42e-1ca7-4bdf-b265-e66c327f8afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Will enable 5 seconds'])[1]/preceding::p[1]</value>
      <webElementGuid>d14918cc-61b4-4b2c-932e-e3b4419fb012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color Change'])[1]/preceding::p[1]</value>
      <webElementGuid>eb2f8b51-784c-42d7-8e1c-49ebc2671267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This text has random Id']/parent::*</value>
      <webElementGuid>253dd727-0f72-4950-b448-1f5335dccae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>9633733b-ce3f-4f27-8f30-372051d7917a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = '32AZ6' and (text() = 'This text has random Id' or . = 'This text has random Id')]</value>
      <webElementGuid>cf0a0eba-7f0f-470e-8f0e-1f235e103674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='5Xmsi']</value>
      <webElementGuid>481b4f40-81e0-48d3-8c82-0403aaa5e477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = '5Xmsi' and (text() = 'This text has random Id' or . = 'This text has random Id')]</value>
      <webElementGuid>ee66fa5c-fb4a-4bc3-93bf-d2a7e3eafcf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
