<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>6c9ccbea-122a-4bd1-885d-8e043053e023</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>header > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/header/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=banner >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>af6ccd1b-f0d1-416d-8034-664d7b8e13b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/Toolsqa.jpg</value>
      <webElementGuid>f1cc6bd4-6ba3-449b-976f-153411065177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/header[1]/a[1]/img[1]</value>
      <webElementGuid>8c974fef-721d-4b6f-aead-86340651a02b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/header/a/img</value>
      <webElementGuid>4a626291-5063-49a7-af71-2520836e5ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/a/img</value>
      <webElementGuid>b9cefb34-7e99-4181-816a-70158387ac70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/Toolsqa.jpg']</value>
      <webElementGuid>64a6eca4-1fb4-4ead-aa73-908f684dfaa9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
